site_name: SeaTable 编程手册
site_author: seatable
docs_dir: ./manual
site_url: https://seatable.github.io/seatable-scripts-cn/


repo_name: seatable/seatable-scripts-cn
repo_url: https://github.com/seatable/seatable-scripts-cn/
edit_uri: edit/master/manual/

copyright: Copyright &copy; 2021 seatable

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - bash
      - javascript
      - python
  # icon:
  logo: assets/logo32_32.png
  favicon: assets/seatable-favicon.ico
  # features:
    # - tabs
  palette:
    primary: deep orange
    accent:

plugins:
  - search # necessary for search to work
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seatable/seatable-scripts-cn/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.superfences


# Page tree
nav:
  - 引言: README.md
  - 对象数据结构: data-structure.md
  - JavaScript 脚本:
    - 引言: javascript/README.md
    - Base: javascript/base.md
    - Output: javascript/output.md
    - Utils: javascript/utils.md
    - Context: javascript/context.md
  - Python 脚本和 API:
    - 引言: python/README.md
    - Base: python/base.md
    - Views: python/views.md
    - Rows: python/rows.md
    - Links: python/links.md
    - Columns: python/columns.md
    - Files: python/files.md
    - Query with SQL: python/query.md
    - Big data storage: python/big_data_storage.md
    - Account: python/account.md
    - Constants: python/constants.md
    - Context: python/context.md
    - Workflow: python/workflow.md
    - User: python/user.md
    - 日期操作: python/dateutils.md
    - 云端环境下支持的库: python/libs.md
    - 消息通知: python/notifications.md
    - 实时获取数据更新通知: python/websocket.md
  - JavaScript API:
    - 引言: javascript-api/README.md
    - Base: javascript-api/base.md
    - Views: javascript-api/views.md
    - Rows: javascript-api/rows.md
    - Links: javascript-api/links.md
    - Columns: javascript-api/columns.md
    - Query with SQL: javascript-api/query.md
    - Constants: javascript-api/constants.md
  - SQL:
    - SQL 语法参考: sql/sql.md
    - SQL 函数参考: sql/function.md
  - 插件开发流程和 API:
    - 插件开发流程: plugins/README.md
    - dtable-sdk:
      - Base: plugins/dtable-sdk/base.md
      - Common: plugins/dtable-sdk/common.md
      - Tables: plugins/dtable-sdk/tables.md
      - Views: plugins/dtable-sdk/views.md
      - Columns: plugins/dtable-sdk/columns.md
      - Rows: plugins/dtable-sdk/rows.md
      - Plugins: plugins/dtable-sdk/plugins.md
      - Links: plugins/dtable-sdk/links.md
    - dtable-utils:
      - Tables: plugins/dtable-utils/tables.md
      - Views: plugins/dtable-utils/views.md
      - Columns: plugins/dtable-utils/columns.md
      - Rows: plugins/dtable-utils/rows.md
      - Cells: plugins/dtable-utils/cells.md
      - Constants: plugins/dtable-utils/constants.md



